# This docker-compose file is for local development only
version: "3.2"
services:
  etcd:
    image: "quay.io/coreos/etcd:${ETCD_VERSION:-v3.3.18}"
    ports:
      - target: 2379
        published: 2379
        mode: host
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://localhost:2379
